function helloworld(){var Q='bootstrap',R='begin',S='gwt.codesvr.helloworld=',T='gwt.codesvr=',U='helloworld',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='Failed to load ',qb='head',rb='meta',sb='name',tb='helloworld::',ub='::',vb='gwt:property',wb='content',xb='=',yb='gwt:onPropertyErrorFn',zb='Bad handler "',Ab='" for "gwt:onPropertyErrorFn"',Bb='gwt:onLoadErrorFn',Cb='" for "gwt:onLoadErrorFn"',Db='#',Eb='?',Fb='/',Gb='img',Hb='clear.cache.gif',Ib='baseUrl',Jb='helloworld.nocache.js',Kb='base',Lb='//',Mb='locale',Nb='en',Ob='locale=',Pb=7,Qb='&',Rb='__gwt_Locale',Sb='_',Tb='Unexpected exception in locale detection, using default: ',Ub=2,Vb=3,Wb='user.agent',Xb='webkit',Yb='safari',Zb='msie',$b=10,_b=11,ac='ie10',bc=9,cc='ie9',dc=8,ec='ie8',fc='gecko',gc='gecko1_8',hc=4,ic='selectingPermutation',jc='helloworld.devmode.js',kc='tn',lc='0C86F14F74BFF562590BBC530074F701',mc='fr',nc='290BBD596054BCED51D549032A4A05B4',oc='29297D1F1EACA842BADDDB48230F2EA6',pc='default',qc='3267EA884601DB2D8A65501F1FAB4E48',rc='32B9C64352538D5F2BEB4021DE4A8F86',sc='3411728E3270F238250F7964933F2DF5',tc='34861477892BA8B7C86C4D7A6C90389D',uc='37139D087480D8D28D47D7A11E2E6B71',vc='3B79D5FF8AE9A4B41087D33B7D117F77',wc='430933724B0C3EE909C11C05E09B69CE',xc='578CB10C831A4FC24125342F3FE063A3',yc='725A988CD2AD9AD54274E7C5F2447C55',zc='9CFF412D1B58DE35EF73E8BEB7ED7C77',Ac='A0F41576F83ABD731928D60D02606957',Bc='A1AF84C411ED04668F0B9F7CFFA071B8',Cc='B004520D9B4D69F6194D7395E0CA861E',Dc='E773FFFC3D5513C9426D9CB4150D307B',Ec='F5FDB57D87AC842362AB21CEE210623F',Fc='FAC1344977430482A1F2F1F812E1B60C',Gc='FEEAC61A9CAFB08A753838214329243E',Hc=':',Ic='.cache.js',Jc='loadExternalRefs',Kc='end',Lc='http:',Mc='file:',Nc='_gwt_dummy_',Oc='__gwtDevModeHook:helloworld',Pc='Ignoring non-whitelisted Dev Mode URL: ',Qc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
helloworld.__sendStats=t;helloworld.__moduleName=U;helloworld.__errFn=null;helloworld.__moduleBase=W;helloworld.__softPermutationId=X;helloworld.__computePropValue=null;helloworld.__getPropMap=null;helloworld.__installRunAsyncCode=function(){};helloworld.__gwtStartLoadingFragment=function(){return null};helloworld.__gwt_isKnownPropertyValue=function(){return false};helloworld.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};helloworld.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[helloworld.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
helloworld.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(helloworld.__errFn){n.onerror=function(){helloworld.__errFn(U,new Error(pb+code))}}r.getElementsByTagName(qb)[X].appendChild(n)}
helloworld.__startLoadingFragment=function(a){return G(a)};helloworld.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(rb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(sb),k;if(j){j=j.replace(tb,db);if(j.indexOf(ub)>=X){continue}if(j==vb){k=i.getAttribute(wb);if(k){var l,m=k.indexOf(xb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==yb){k=i.getAttribute(wb);if(k){try{d=eval(k)}catch(a){alert(zb+k+Ab)}}}else if(j==Bb){k=i.getAttribute(wb);if(k){try{e=eval(k)}catch(a){alert(zb+k+Cb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;helloworld.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Db);if(b==-1){b=a.length}var c=a.indexOf(Eb);if(c==-1){c=a.length}var d=a.lastIndexOf(Fb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Gb);b.src=a+Hb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Ib);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Jb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Kb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Lb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return helloworld.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Mb]=function(){var b=null;var c=Nb;try{if(!b){var d=location.search;var e=d.indexOf(Ob);if(e>=X){var f=d.substring(e+Pb);var g=d.indexOf(Qb,e);if(g<X){g=d.length}b=d.substring(e+Pb,g)}}if(!b){b=__gwt_getMetaProperty(Mb)}if(!b){b=q[Rb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Mb,b)){var h=b.lastIndexOf(Sb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Tb+a)}q[Rb]=c;return b||Nb};l[Mb]={'default':X,en:Y,fr:Ub,tn:Vb};m[Wb]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Xb)!=-1}())return Yb;if(function(){return a.indexOf(Zb)!=-1&&(b>=$b&&b<_b)}())return ac;if(function(){return a.indexOf(Zb)!=-1&&(b>=bc&&b<_b)}())return cc;if(function(){return a.indexOf(Zb)!=-1&&(b>=dc&&b<_b)}())return ec;if(function(){return a.indexOf(fc)!=-1||b>=_b}())return gc;return db};l[Wb]={gecko1_8:X,ie10:Y,ie8:Ub,ie9:Vb,safari:hc};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};helloworld.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};helloworld.__computePropValue=n;q.__gwt_activeModules[U].bindings=helloworld.__getPropMap;t(Q,ic);if(s()){return G(jc)}var o;try{k([kc,gc],lc);k([mc,Yb],nc);k([mc,ec],oc);k([pc,ec],qc);k([pc,Yb],rc);k([Nb,cc],sc);k([mc,cc],tc);k([kc,ac],uc);k([kc,Yb],vc);k([Nb,ec],wc);k([Nb,Yb],xc);k([pc,cc],yc);k([Nb,ac],zc);k([pc,gc],Ac);k([pc,ac],Bc);k([mc,gc],Cc);k([kc,cc],Dc);k([mc,ac],Ec);k([kc,ec],Fc);k([Nb,gc],Gc);o=i[n(Mb)][n(Wb)];var p=o.indexOf(Hc);if(p!=-1){j=parseInt(o.substring(p+Y),$b);o=o.substring(X,p)}}catch(a){}helloworld.__softPermutationId=j;return G(o+Ic)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}t(Jc,R);t(Jc,Kc)}
D();helloworld.__moduleBase=F();v[U].moduleBase=helloworld.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Lc||q.location.protocol==Mc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Nc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Oc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Pc+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+Qc]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(qb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Kc);C(J);return true}
helloworld.succeeded=helloworld();